package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

const (
	// DefaultProfileLabel is the label key used on namespaces to opt in and
	// pick a profile defined in a SlumlordAutoSchedulePolicy. The label value
	// selects the profile.
	DefaultProfileLabel = "slumlord.io/sleep-profile"

	// DefaultGeneratedScheduleName is the default name used for the
	// SlumlordSleepSchedule resources created by an AutoSchedulePolicy.
	DefaultGeneratedScheduleName = "auto-sleep"

	// ManagedByLabel is set on SleepSchedules generated by a policy. Its value
	// is the policy name. It serves as the cross-namespace ownership marker
	// (Kubernetes forbids cross-namespace ownerReferences).
	ManagedByLabel = "slumlord.io/managed-by-policy"

	// AutoSchedulePolicyFinalizer ensures generated SleepSchedules are deleted
	// before the policy itself is removed from the API server.
	AutoSchedulePolicyFinalizer = "slumlord.io/auto-schedule-policy"
)

// SlumlordAutoSchedulePolicySpec defines the desired state of SlumlordAutoSchedulePolicy.
type SlumlordAutoSchedulePolicySpec struct {
	// Suspend pauses reconciliation when true. Existing generated schedules
	// remain in place but are no longer kept in sync with the policy template.
	// +optional
	Suspend bool `json:"suspend,omitempty"`

	// NamespaceSelector restricts which namespaces this policy applies to.
	// If empty, defaults to: matchExpressions: [{key: <profileLabel>, operator: Exists}]
	// so only namespaces explicitly carrying the profile label are matched.
	// +optional
	NamespaceSelector *metav1.LabelSelector `json:"namespaceSelector,omitempty"`

	// ProfileLabel is the namespace label whose value selects a profile from
	// spec.profiles. Defaults to "slumlord.io/sleep-profile".
	// +optional
	ProfileLabel string `json:"profileLabel,omitempty"`

	// Profiles is a map of profile name -> SleepSchedule template. A namespace
	// is auto-scheduled by setting the profile label to one of these keys.
	// +kubebuilder:validation:MinProperties=1
	Profiles map[string]AutoScheduleProfile `json:"profiles"`

	// GeneratedName is the name of the SlumlordSleepSchedule created in each
	// matched namespace. Defaults to "auto-sleep". Must be a valid DNS-1123
	// subdomain.
	// +optional
	GeneratedName string `json:"generatedName,omitempty"`

	// ReconcileInterval overrides the default reconciliation interval.
	// +optional
	ReconcileInterval *metav1.Duration `json:"reconcileInterval,omitempty"`
}

// AutoScheduleProfile is the template used to materialize a SleepSchedule.
// It mirrors the user-facing fields of SlumlordSleepScheduleSpec.
type AutoScheduleProfile struct {
	// Selector specifies which workloads to target in each matched namespace.
	Selector WorkloadSelector `json:"selector"`

	// Schedules defines one or more sleep windows. Workloads sleep if ANY
	// window matches the current time.
	// +kubebuilder:validation:MinItems=1
	Schedules []SleepWindow `json:"schedules"`

	// Suspend is forwarded onto every generated SleepSchedule when true.
	// +optional
	Suspend bool `json:"suspend,omitempty"`
}

// SlumlordAutoSchedulePolicyStatus reports policy-level reconciliation health.
type SlumlordAutoSchedulePolicyStatus struct {
	// ObservedGeneration reflects the generation most recently reconciled.
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// MatchedNamespaces is the count of namespaces this policy matched at the
	// last reconcile.
	// +optional
	MatchedNamespaces int32 `json:"matchedNamespaces,omitempty"`

	// GeneratedSchedules is the count of SleepSchedules currently owned by
	// this policy (managed-by label points back at the policy).
	// +optional
	GeneratedSchedules int32 `json:"generatedSchedules,omitempty"`

	// Conflicts lists namespaces where this policy would generate a schedule
	// but another policy already matches the same namespace, or where a
	// non-managed SleepSchedule with the same name already exists.
	// +optional
	Conflicts []NamespaceConflict `json:"conflicts,omitempty"`

	// MissingProfiles lists namespaces whose profile label value does not
	// match any of the profiles declared in spec.profiles.
	// +optional
	MissingProfiles []MissingProfile `json:"missingProfiles,omitempty"`

	// Conditions represent the latest available observations.
	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// NamespaceConflict describes why a namespace was skipped.
type NamespaceConflict struct {
	// Namespace whose reconciliation was skipped.
	Namespace string `json:"namespace"`

	// Reason machine-readable code (e.g. PolicyOverlap, ManualScheduleExists).
	Reason string `json:"reason"`

	// WithPolicies lists the other policies that also match this namespace,
	// when Reason == PolicyOverlap.
	// +optional
	WithPolicies []string `json:"withPolicies,omitempty"`

	// Message is a human-readable explanation.
	// +optional
	Message string `json:"message,omitempty"`
}

// MissingProfile describes a namespace whose label points at an undefined profile.
type MissingProfile struct {
	// Namespace whose reconciliation was skipped.
	Namespace string `json:"namespace"`

	// Profile is the label value that did not match any declared profile.
	Profile string `json:"profile"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,shortName=slasp
// +kubebuilder:printcolumn:name="Suspended",type="boolean",JSONPath=".spec.suspend"
// +kubebuilder:printcolumn:name="Matched",type="integer",JSONPath=".status.matchedNamespaces"
// +kubebuilder:printcolumn:name="Generated",type="integer",JSONPath=".status.generatedSchedules"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"

// SlumlordAutoSchedulePolicy is the Schema for the slumlordautoschedulepolicies API.
type SlumlordAutoSchedulePolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   SlumlordAutoSchedulePolicySpec   `json:"spec,omitempty"`
	Status SlumlordAutoSchedulePolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SlumlordAutoSchedulePolicyList contains a list of SlumlordAutoSchedulePolicy
type SlumlordAutoSchedulePolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SlumlordAutoSchedulePolicy `json:"items"`
}

// ResolvedProfileLabel returns the profile label key, falling back to the
// default when spec.profileLabel is empty.
func (p *SlumlordAutoSchedulePolicy) ResolvedProfileLabel() string {
	if p.Spec.ProfileLabel != "" {
		return p.Spec.ProfileLabel
	}
	return DefaultProfileLabel
}

// ResolvedGeneratedName returns the SleepSchedule name to create, falling back
// to the default when spec.generatedName is empty.
func (p *SlumlordAutoSchedulePolicy) ResolvedGeneratedName() string {
	if p.Spec.GeneratedName != "" {
		return p.Spec.GeneratedName
	}
	return DefaultGeneratedScheduleName
}

func init() {
	SchemeBuilder.Register(&SlumlordAutoSchedulePolicy{}, &SlumlordAutoSchedulePolicyList{})
}
