//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BinPackerThresholds) DeepCopyInto(out *BinPackerThresholds) {
	*out = *in
	if in.CPURequestPercent != nil {
		in, out := &in.CPURequestPercent, &out.CPURequestPercent
		*out = new(int32)
		**out = **in
	}
	if in.MemoryRequestPercent != nil {
		in, out := &in.MemoryRequestPercent, &out.MemoryRequestPercent
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BinPackerThresholds.
func (in *BinPackerThresholds) DeepCopy() *BinPackerThresholds {
	if in == nil {
		return nil
	}
	out := new(BinPackerThresholds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CandidateNode) DeepCopyInto(out *CandidateNode) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CandidateNode.
func (in *CandidateNode) DeepCopy() *CandidateNode {
	if in == nil {
		return nil
	}
	out := new(CandidateNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainConfig) DeepCopyInto(out *DrainConfig) {
	*out = *in
	if in.GracePeriodSeconds != nil {
		in, out := &in.GracePeriodSeconds, &out.GracePeriodSeconds
		*out = new(int64)
		**out = **in
	}
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		*out = new(int32)
		**out = **in
	}
	if in.IgnoreDaemonSets != nil {
		in, out := &in.IgnoreDaemonSets, &out.IgnoreDaemonSets
		*out = new(bool)
		**out = **in
	}
	if in.PodSelector != nil {
		in, out := &in.PodSelector, &out.PodSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainConfig.
func (in *DrainConfig) DeepCopy() *DrainConfig {
	if in == nil {
		return nil
	}
	out := new(DrainConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainNodeResult) DeepCopyInto(out *DrainNodeResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainNodeResult.
func (in *DrainNodeResult) DeepCopy() *DrainNodeResult {
	if in == nil {
		return nil
	}
	out := new(DrainNodeResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainRunStatus) DeepCopyInto(out *DrainRunStatus) {
	*out = *in
	in.StartTime.DeepCopyInto(&out.StartTime)
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.NodeResults != nil {
		in, out := &in.NodeResults, &out.NodeResults
		*out = make([]DrainNodeResult, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainRunStatus.
func (in *DrainRunStatus) DeepCopy() *DrainRunStatus {
	if in == nil {
		return nil
	}
	out := new(DrainRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainSafety) DeepCopyInto(out *DrainSafety) {
	*out = *in
	if in.MaxNodesPerRun != nil {
		in, out := &in.MaxNodesPerRun, &out.MaxNodesPerRun
		*out = new(int32)
		**out = **in
	}
	if in.MinReadyNodes != nil {
		in, out := &in.MinReadyNodes, &out.MinReadyNodes
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainSafety.
func (in *DrainSafety) DeepCopy() *DrainSafety {
	if in == nil {
		return nil
	}
	out := new(DrainSafety)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainSchedule) DeepCopyInto(out *DrainSchedule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainSchedule.
func (in *DrainSchedule) DeepCopy() *DrainSchedule {
	if in == nil {
		return nil
	}
	out := new(DrainSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainThresholds) DeepCopyInto(out *DrainThresholds) {
	*out = *in
	if in.CPURequestPercent != nil {
		in, out := &in.CPURequestPercent, &out.CPURequestPercent
		*out = new(int32)
		**out = **in
	}
	if in.MemoryRequestPercent != nil {
		in, out := &in.MemoryRequestPercent, &out.MemoryRequestPercent
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainThresholds.
func (in *DrainThresholds) DeepCopy() *DrainThresholds {
	if in == nil {
		return nil
	}
	out := new(DrainThresholds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdleThresholds) DeepCopyInto(out *IdleThresholds) {
	*out = *in
	if in.CPUPercent != nil {
		in, out := &in.CPUPercent, &out.CPUPercent
		*out = new(int32)
		**out = **in
	}
	if in.MemoryPercent != nil {
		in, out := &in.MemoryPercent, &out.MemoryPercent
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdleThresholds.
func (in *IdleThresholds) DeepCopy() *IdleThresholds {
	if in == nil {
		return nil
	}
	out := new(IdleThresholds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdleWorkload) DeepCopyInto(out *IdleWorkload) {
	*out = *in
	in.IdleSince.DeepCopyInto(&out.IdleSince)
	if in.CurrentCPUPercent != nil {
		in, out := &in.CurrentCPUPercent, &out.CurrentCPUPercent
		*out = new(int32)
		**out = **in
	}
	if in.CurrentMemoryPercent != nil {
		in, out := &in.CurrentMemoryPercent, &out.CurrentMemoryPercent
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdleWorkload.
func (in *IdleWorkload) DeepCopy() *IdleWorkload {
	if in == nil {
		return nil
	}
	out := new(IdleWorkload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedWorkload) DeepCopyInto(out *ManagedWorkload) {
	*out = *in
	if in.OriginalReplicas != nil {
		in, out := &in.OriginalReplicas, &out.OriginalReplicas
		*out = new(int32)
		**out = **in
	}
	if in.OriginalSuspend != nil {
		in, out := &in.OriginalSuspend, &out.OriginalSuspend
		*out = new(bool)
		**out = **in
	}
	if in.OriginalHibernation != nil {
		in, out := &in.OriginalHibernation, &out.OriginalHibernation
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedWorkload.
func (in *ManagedWorkload) DeepCopy() *ManagedWorkload {
	if in == nil {
		return nil
	}
	out := new(ManagedWorkload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlannedEviction) DeepCopyInto(out *PlannedEviction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlannedEviction.
func (in *PlannedEviction) DeepCopy() *PlannedEviction {
	if in == nil {
		return nil
	}
	out := new(PlannedEviction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaledWorkload) DeepCopyInto(out *ScaledWorkload) {
	*out = *in
	if in.OriginalReplicas != nil {
		in, out := &in.OriginalReplicas, &out.OriginalReplicas
		*out = new(int32)
		**out = **in
	}
	if in.OriginalSuspend != nil {
		in, out := &in.OriginalSuspend, &out.OriginalSuspend
		*out = new(bool)
		**out = **in
	}
	in.ScaledAt.DeepCopyInto(&out.ScaledAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaledWorkload.
func (in *ScaledWorkload) DeepCopy() *ScaledWorkload {
	if in == nil {
		return nil
	}
	out := new(ScaledWorkload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SleepWindow) DeepCopyInto(out *SleepWindow) {
	*out = *in
	if in.Days != nil {
		in, out := &in.Days, &out.Days
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SleepWindow.
func (in *SleepWindow) DeepCopy() *SleepWindow {
	if in == nil {
		return nil
	}
	out := new(SleepWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlumlordBinPacker) DeepCopyInto(out *SlumlordBinPacker) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlumlordBinPacker.
func (in *SlumlordBinPacker) DeepCopy() *SlumlordBinPacker {
	if in == nil {
		return nil
	}
	out := new(SlumlordBinPacker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlumlordBinPacker) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlumlordBinPackerList) DeepCopyInto(out *SlumlordBinPackerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SlumlordBinPacker, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlumlordBinPackerList.
func (in *SlumlordBinPackerList) DeepCopy() *SlumlordBinPackerList {
	if in == nil {
		return nil
	}
	out := new(SlumlordBinPackerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlumlordBinPackerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlumlordBinPackerSpec) DeepCopyInto(out *SlumlordBinPackerSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeNamespaces != nil {
		in, out := &in.ExcludeNamespaces, &out.ExcludeNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Thresholds.DeepCopyInto(&out.Thresholds)
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(SleepWindow)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxEvictionsPerCycle != nil {
		in, out := &in.MaxEvictionsPerCycle, &out.MaxEvictionsPerCycle
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlumlordBinPackerSpec.
func (in *SlumlordBinPackerSpec) DeepCopy() *SlumlordBinPackerSpec {
	if in == nil {
		return nil
	}
	out := new(SlumlordBinPackerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlumlordBinPackerStatus) DeepCopyInto(out *SlumlordBinPackerStatus) {
	*out = *in
	if in.CandidateNodes != nil {
		in, out := &in.CandidateNodes, &out.CandidateNodes
		*out = make([]CandidateNode, len(*in))
		copy(*out, *in)
	}
	if in.ConsolidationPlan != nil {
		in, out := &in.ConsolidationPlan, &out.ConsolidationPlan
		*out = make([]PlannedEviction, len(*in))
		copy(*out, *in)
	}
	if in.LastAnalysisTime != nil {
		in, out := &in.LastAnalysisTime, &out.LastAnalysisTime
		*out = (*in).DeepCopy()
	}
	if in.LastConsolidationTime != nil {
		in, out := &in.LastConsolidationTime, &out.LastConsolidationTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlumlordBinPackerStatus.
func (in *SlumlordBinPackerStatus) DeepCopy() *SlumlordBinPackerStatus {
	if in == nil {
		return nil
	}
	out := new(SlumlordBinPackerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlumlordIdleDetector) DeepCopyInto(out *SlumlordIdleDetector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlumlordIdleDetector.
func (in *SlumlordIdleDetector) DeepCopy() *SlumlordIdleDetector {
	if in == nil {
		return nil
	}
	out := new(SlumlordIdleDetector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlumlordIdleDetector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlumlordIdleDetectorList) DeepCopyInto(out *SlumlordIdleDetectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SlumlordIdleDetector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlumlordIdleDetectorList.
func (in *SlumlordIdleDetectorList) DeepCopy() *SlumlordIdleDetectorList {
	if in == nil {
		return nil
	}
	out := new(SlumlordIdleDetectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlumlordIdleDetectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlumlordIdleDetectorSpec) DeepCopyInto(out *SlumlordIdleDetectorSpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	in.Thresholds.DeepCopyInto(&out.Thresholds)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlumlordIdleDetectorSpec.
func (in *SlumlordIdleDetectorSpec) DeepCopy() *SlumlordIdleDetectorSpec {
	if in == nil {
		return nil
	}
	out := new(SlumlordIdleDetectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlumlordIdleDetectorStatus) DeepCopyInto(out *SlumlordIdleDetectorStatus) {
	*out = *in
	if in.IdleWorkloads != nil {
		in, out := &in.IdleWorkloads, &out.IdleWorkloads
		*out = make([]IdleWorkload, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ScaledWorkloads != nil {
		in, out := &in.ScaledWorkloads, &out.ScaledWorkloads
		*out = make([]ScaledWorkload, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastCheckTime != nil {
		in, out := &in.LastCheckTime, &out.LastCheckTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlumlordIdleDetectorStatus.
func (in *SlumlordIdleDetectorStatus) DeepCopy() *SlumlordIdleDetectorStatus {
	if in == nil {
		return nil
	}
	out := new(SlumlordIdleDetectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlumlordNodeDrainPolicy) DeepCopyInto(out *SlumlordNodeDrainPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlumlordNodeDrainPolicy.
func (in *SlumlordNodeDrainPolicy) DeepCopy() *SlumlordNodeDrainPolicy {
	if in == nil {
		return nil
	}
	out := new(SlumlordNodeDrainPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlumlordNodeDrainPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlumlordNodeDrainPolicyList) DeepCopyInto(out *SlumlordNodeDrainPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SlumlordNodeDrainPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlumlordNodeDrainPolicyList.
func (in *SlumlordNodeDrainPolicyList) DeepCopy() *SlumlordNodeDrainPolicyList {
	if in == nil {
		return nil
	}
	out := new(SlumlordNodeDrainPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlumlordNodeDrainPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlumlordNodeDrainPolicySpec) DeepCopyInto(out *SlumlordNodeDrainPolicySpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Thresholds.DeepCopyInto(&out.Thresholds)
	out.Schedule = in.Schedule
	in.Drain.DeepCopyInto(&out.Drain)
	in.Safety.DeepCopyInto(&out.Safety)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlumlordNodeDrainPolicySpec.
func (in *SlumlordNodeDrainPolicySpec) DeepCopy() *SlumlordNodeDrainPolicySpec {
	if in == nil {
		return nil
	}
	out := new(SlumlordNodeDrainPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlumlordNodeDrainPolicyStatus) DeepCopyInto(out *SlumlordNodeDrainPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastRun != nil {
		in, out := &in.LastRun, &out.LastRun
		*out = new(DrainRunStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.NextRun != nil {
		in, out := &in.NextRun, &out.NextRun
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlumlordNodeDrainPolicyStatus.
func (in *SlumlordNodeDrainPolicyStatus) DeepCopy() *SlumlordNodeDrainPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(SlumlordNodeDrainPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlumlordSleepSchedule) DeepCopyInto(out *SlumlordSleepSchedule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlumlordSleepSchedule.
func (in *SlumlordSleepSchedule) DeepCopy() *SlumlordSleepSchedule {
	if in == nil {
		return nil
	}
	out := new(SlumlordSleepSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlumlordSleepSchedule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlumlordSleepScheduleList) DeepCopyInto(out *SlumlordSleepScheduleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SlumlordSleepSchedule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlumlordSleepScheduleList.
func (in *SlumlordSleepScheduleList) DeepCopy() *SlumlordSleepScheduleList {
	if in == nil {
		return nil
	}
	out := new(SlumlordSleepScheduleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlumlordSleepScheduleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlumlordSleepScheduleSpec) DeepCopyInto(out *SlumlordSleepScheduleSpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	in.Schedule.DeepCopyInto(&out.Schedule)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlumlordSleepScheduleSpec.
func (in *SlumlordSleepScheduleSpec) DeepCopy() *SlumlordSleepScheduleSpec {
	if in == nil {
		return nil
	}
	out := new(SlumlordSleepScheduleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlumlordSleepScheduleStatus) DeepCopyInto(out *SlumlordSleepScheduleStatus) {
	*out = *in
	if in.ManagedWorkloads != nil {
		in, out := &in.ManagedWorkloads, &out.ManagedWorkloads
		*out = make([]ManagedWorkload, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlumlordSleepScheduleStatus.
func (in *SlumlordSleepScheduleStatus) DeepCopy() *SlumlordSleepScheduleStatus {
	if in == nil {
		return nil
	}
	out := new(SlumlordSleepScheduleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadSelector) DeepCopyInto(out *WorkloadSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MatchNames != nil {
		in, out := &in.MatchNames, &out.MatchNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Types != nil {
		in, out := &in.Types, &out.Types
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadSelector.
func (in *WorkloadSelector) DeepCopy() *WorkloadSelector {
	if in == nil {
		return nil
	}
	out := new(WorkloadSelector)
	in.DeepCopyInto(out)
	return out
}
