//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedWorkload) DeepCopyInto(out *ManagedWorkload) {
	*out = *in
	if in.OriginalReplicas != nil {
		in, out := &in.OriginalReplicas, &out.OriginalReplicas
		*out = new(int32)
		**out = **in
	}
	if in.OriginalSuspend != nil {
		in, out := &in.OriginalSuspend, &out.OriginalSuspend
		*out = new(bool)
		**out = **in
	}
	if in.OriginalHibernation != nil {
		in, out := &in.OriginalHibernation, &out.OriginalHibernation
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedWorkload.
func (in *ManagedWorkload) DeepCopy() *ManagedWorkload {
	if in == nil {
		return nil
	}
	out := new(ManagedWorkload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SleepWindow) DeepCopyInto(out *SleepWindow) {
	*out = *in
	if in.Days != nil {
		in, out := &in.Days, &out.Days
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SleepWindow.
func (in *SleepWindow) DeepCopy() *SleepWindow {
	if in == nil {
		return nil
	}
	out := new(SleepWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlumlordSleepSchedule) DeepCopyInto(out *SlumlordSleepSchedule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlumlordSleepSchedule.
func (in *SlumlordSleepSchedule) DeepCopy() *SlumlordSleepSchedule {
	if in == nil {
		return nil
	}
	out := new(SlumlordSleepSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlumlordSleepSchedule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlumlordSleepScheduleList) DeepCopyInto(out *SlumlordSleepScheduleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SlumlordSleepSchedule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlumlordSleepScheduleList.
func (in *SlumlordSleepScheduleList) DeepCopy() *SlumlordSleepScheduleList {
	if in == nil {
		return nil
	}
	out := new(SlumlordSleepScheduleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlumlordSleepScheduleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlumlordSleepScheduleSpec) DeepCopyInto(out *SlumlordSleepScheduleSpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	in.Schedule.DeepCopyInto(&out.Schedule)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlumlordSleepScheduleSpec.
func (in *SlumlordSleepScheduleSpec) DeepCopy() *SlumlordSleepScheduleSpec {
	if in == nil {
		return nil
	}
	out := new(SlumlordSleepScheduleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlumlordSleepScheduleStatus) DeepCopyInto(out *SlumlordSleepScheduleStatus) {
	*out = *in
	if in.ManagedWorkloads != nil {
		in, out := &in.ManagedWorkloads, &out.ManagedWorkloads
		*out = make([]ManagedWorkload, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlumlordSleepScheduleStatus.
func (in *SlumlordSleepScheduleStatus) DeepCopy() *SlumlordSleepScheduleStatus {
	if in == nil {
		return nil
	}
	out := new(SlumlordSleepScheduleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadSelector) DeepCopyInto(out *WorkloadSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MatchNames != nil {
		in, out := &in.MatchNames, &out.MatchNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Types != nil {
		in, out := &in.Types, &out.Types
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadSelector.
func (in *WorkloadSelector) DeepCopy() *WorkloadSelector {
	if in == nil {
		return nil
	}
	out := new(WorkloadSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdleThresholds) DeepCopyInto(out *IdleThresholds) {
	*out = *in
	if in.CPUPercent != nil {
		in, out := &in.CPUPercent, &out.CPUPercent
		*out = new(int32)
		**out = **in
	}
	if in.MemoryPercent != nil {
		in, out := &in.MemoryPercent, &out.MemoryPercent
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdleThresholds.
func (in *IdleThresholds) DeepCopy() *IdleThresholds {
	if in == nil {
		return nil
	}
	out := new(IdleThresholds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdleWorkload) DeepCopyInto(out *IdleWorkload) {
	*out = *in
	in.IdleSince.DeepCopyInto(&out.IdleSince)
	if in.CurrentCPUPercent != nil {
		in, out := &in.CurrentCPUPercent, &out.CurrentCPUPercent
		*out = new(int32)
		**out = **in
	}
	if in.CurrentMemoryPercent != nil {
		in, out := &in.CurrentMemoryPercent, &out.CurrentMemoryPercent
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdleWorkload.
func (in *IdleWorkload) DeepCopy() *IdleWorkload {
	if in == nil {
		return nil
	}
	out := new(IdleWorkload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaledWorkload) DeepCopyInto(out *ScaledWorkload) {
	*out = *in
	if in.OriginalReplicas != nil {
		in, out := &in.OriginalReplicas, &out.OriginalReplicas
		*out = new(int32)
		**out = **in
	}
	if in.OriginalSuspend != nil {
		in, out := &in.OriginalSuspend, &out.OriginalSuspend
		*out = new(bool)
		**out = **in
	}
	in.ScaledAt.DeepCopyInto(&out.ScaledAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaledWorkload.
func (in *ScaledWorkload) DeepCopy() *ScaledWorkload {
	if in == nil {
		return nil
	}
	out := new(ScaledWorkload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlumlordIdleDetector) DeepCopyInto(out *SlumlordIdleDetector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlumlordIdleDetector.
func (in *SlumlordIdleDetector) DeepCopy() *SlumlordIdleDetector {
	if in == nil {
		return nil
	}
	out := new(SlumlordIdleDetector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlumlordIdleDetector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlumlordIdleDetectorList) DeepCopyInto(out *SlumlordIdleDetectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SlumlordIdleDetector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlumlordIdleDetectorList.
func (in *SlumlordIdleDetectorList) DeepCopy() *SlumlordIdleDetectorList {
	if in == nil {
		return nil
	}
	out := new(SlumlordIdleDetectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SlumlordIdleDetectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlumlordIdleDetectorSpec) DeepCopyInto(out *SlumlordIdleDetectorSpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	in.Thresholds.DeepCopyInto(&out.Thresholds)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlumlordIdleDetectorSpec.
func (in *SlumlordIdleDetectorSpec) DeepCopy() *SlumlordIdleDetectorSpec {
	if in == nil {
		return nil
	}
	out := new(SlumlordIdleDetectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlumlordIdleDetectorStatus) DeepCopyInto(out *SlumlordIdleDetectorStatus) {
	*out = *in
	if in.IdleWorkloads != nil {
		in, out := &in.IdleWorkloads, &out.IdleWorkloads
		*out = make([]IdleWorkload, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ScaledWorkloads != nil {
		in, out := &in.ScaledWorkloads, &out.ScaledWorkloads
		*out = make([]ScaledWorkload, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastCheckTime != nil {
		in, out := &in.LastCheckTime, &out.LastCheckTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlumlordIdleDetectorStatus.
func (in *SlumlordIdleDetectorStatus) DeepCopy() *SlumlordIdleDetectorStatus {
	if in == nil {
		return nil
	}
	out := new(SlumlordIdleDetectorStatus)
	in.DeepCopyInto(out)
	return out
}
